"""add clio tokens to user

Revision ID: 551ba2044342
Revises: 3401b2c4e107
Create Date: 2026-03-03 17:52:47.594649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551ba2044342'
down_revision: Union[str, Sequence[str], None] = '3401b2c4e107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clio_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('clio_refresh_token', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'USER', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'clio_refresh_token')
    op.drop_column('users', 'clio_access_token')
    # ### end Alembic commands ###
